<?php

namespace Repository;

use Kdyby\Doctrine\EntityDao;
use Kdyby\Doctrine\EntityManager;
use Nette\Http\FileUpload;
use UW\Core\ORM\Repository;

/**
 * Quiz Repository class
 */
class Quiz extends Repository\CoreRepository
{
	/** @var EntityManager */
	private $entityManager;

	/** @var EntityDao */
	private $dao;

	/**
	 * Quiz constructor.
	 * @param EntityManager $entityManager
	 */
	public function __construct(EntityManager $entityManager)
	{
		$this->entityManager = $entityManager;
		$this->dao = $this->entityManager->getRepository(\Entity\Quiz::getClassName());
	}

    private function uploadFiles(array &$data)
    {
        /** @var FileUpload $container */
        foreach ($data["quiz_question"] as $key => &$container) {
            /** @var FileUpload $file */
            $file =  @$container["file_path"];

            if ($file == NULL) {
                continue;
            }

            if ($file->getName() == "") {
                $data["quiz_question"][$key]["file_path"] = NULL;
                continue;
            }

            $file->move(WWW_DIR . DS . "files" . DS . $file->getName());

            $data["quiz_question"][$key]["file_path"] = $file->getName();

        }
	}

    protected function getJoins(\Kdyby\Doctrine\QueryBuilder &$query)
    {
        $query->addSelect("quiz_question")
            ->leftJoin("u.quiz_question", "quiz_question");
    }


    public function insertForm(array $data)
    {
        $this->uploadFiles($data);

        return parent::insertForm($data); // TODO: Change the autogenerated stub
    }

    public function updateForm(array $data, $id = NULL)
    {
        $this->uploadFiles($data);

        return parent::updateForm($data, $id); // TODO: Change the autogenerated stub
    }

    /**
	 * @return EntityManager
	 */
	protected function getEntityManager()
	{
		return $this->entityManager;
	}


	/**
	 * @return EntityDao
	 */
	public function getDao()
	{
		return $this->dao;
	}
}

