<?php

namespace Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlacesRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class PlacesRepository extends EntityRepository
{
}
